### ISSUE TITLE
[1.10.2] Problems on Startup

### ISSUE THREAD

**Issue by ParaMotor** [Alec-WAM/CrystalMod#1]
First of all, it would be better if you make your mod needing TConstruct and EnderIO on Curse. With this option, Curse would download automatically both mods. That would help for some people who can't read crash logs. If TConstruct and EnderIO aren't important for this mod, you should change your code, that your mod doesn't try to load things from both mods as long as they aren't installed.
Example:
http://pastebin.com/Q0ex3Pyk

Second, I have another unsolved crash on Startup:
http://pastebin.com/PpUZUDTk

using forge 12.18.3.2221

**Comment by Alec-WAM** [comment]
Tinkers Construct or EnderIO should now just be optional mods.
