### ISSUE TITLE
Ender Buffers Don't Seem To Work

### ISSUE THREAD

**Issue by ScytheIronclaw** [Alec-WAM/CrystalMod#13]
Minecraft Version: 1.11.2
Forge Version: 13.20.0.2252
Mod Version: 1.11.2-4.4.0dev

Is this on a server yes/no:   no

Crash Log(s) if applicable (pastebin or git):  

Ender Buffers don't connect to any device or machine that uses CU or RF.
Ender Buffer's don't connect to CU or RF Crystal Pipes, and don't connect to Item or liquid Crystal Pipes.
Ender Buffers don't have an interface when right-clicked either.

Steps to reproduce:  
1.    Place down an Ender Buffer
2.   Attempt to connect CU Crystal Pipes or RF Pipes, or any Crystal Pipes

**Comment by Alec-WAM** [comment]
That is intentional. If you open the GUI and look at the tab on the side that allows you to configure the input and output of the resource it would be disabled. Change that to anything other than disabled and things should be allowed to connect. If you want me to allow them to connect in any of the IO modes let me know.

**Comment by ScytheIronclaw** [comment]
That's the thing though. The Ender Buffer's GUI must be affected by the same bug as the Crystal Workbench and Backpacks. When I right click them, they don't have an interface.

I'm assuming their intended interface would be like the Teserects.
The main window would have a field to enter a name, A window above that would be for selecting a network, or adding or removing a network.
The tab must be for deciding how it transfers stuff; energy in/out. liquid in/out, items in/out.

When right-clicking the Ender Buffer nothing happens. I even tried right-clicking it with the wrench the mod adds, nothing.

**Comment by Alec-WAM** [comment]
Huh. I will have to look into that.
