### ISSUE TITLE
Crystal Backpacks do not open their Inventory when right-clicked.

### ISSUE THREAD

**Issue by ScytheIronclaw** [Alec-WAM/CrystalMod#17]
Minecraft Version 1.11.2
Forge Version 13.20.0.2252
Mod Version: 1.11.2-4.5.0dev

Is this on a server yes/no:  no

Crash Log(s) if applicable (pastebin or git):  

Crystal Backpacks (any tier) do not open an inventory when right-clicked.

Steps to reproduce:  
1.    Create or Spawn in a Backpack from the Crystal Mod
2.    Select it and right click
3.

**Comment by Alec-WAM** [comment]
I tried to reproduce this and it was working fine for me. Is anything printing out in the log?

**Comment by ScytheIronclaw** [comment]
All backpacks are bugged for me.
I right click and nothing happens.
You using MC Forge 13.20.0.2252?

I spawned them in Creative and crafted them.
The instance I'm using to debug with only have Inventory Tweaks, Mouse Tweaks, Journeymap and CrystalMod

Here's the latest FML Log
[fml-client-latest.txt](https://github.com/Alec-WAM/CrystalMod/files/820226/fml-client-latest.txt)

**Comment by Alec-WAM** [comment]
![2017-03-06_21 18 38](https://cloud.githubusercontent.com/assets/7232670/23640335/8602d09a-02b2-11e7-9302-fc9dbfedc15e.png)
![2017-03-06_21 18 16](https://cloud.githubusercontent.com/assets/7232670/23640334/85fe9f20-02b2-11e7-875b-7c90d07df8bb.png)
![2017-03-06_21 18 19](https://cloud.githubusercontent.com/assets/7232670/23640336/860342be-02b2-11e7-81cb-f82e164602a8.png)

Here is the backpacks working in Forge 13.20.0.2253. My only guess is that either MouseTweaks or InventoryTweaks is causing the issue.
