### ISSUE TITLE
crystalmod{1.0.0dev1} crashes dedicated Forge 1.11.2 build 2226 on startup

### ISSUE THREAD

**Issue by kreezxil** [Alec-WAM/CrystalMod#2]
Notes:
     appears to be looking for client side classes

crash report:
https://gist.github.com/5fcfb9b6d6cfcaf52a66f80b1db1a870

fml server latest:
https://gist.github.com/5471a317ef712d542dec1d74de70a638

**Comment by Alec-WAM** [comment]
Ok I think I fixed the issue. I will build and publish the fix and let me know if it happens again.

**Comment by kreezxil** [comment]
still same crash, here is new report:

Issue:  crystalmod{1.11.2-4.0.1-dev1} crashes dedicated Forge 1.11.2 build 2226 on startup

Notes:
     says No Class Def Found Error -- makes me think it's looking for a client like it don't know it's running on a server

crash report:
https://gist.github.com/b08751bbf703e556e13885ab21c3c95b

fml server latest:
https://gist.github.com/0383529b117f33228b1228aeff2ab258

**Comment by Alec-WAM** [comment]
Debugged in a test server. It should now completely launch and pass a phases.

**Comment by kreezxil** [comment]
yep it doesn't crash on startup but now it doesn't allow a player to connect to it.

dedicated server stack trace: http://pastebin.com/4V6GWVsX

**Comment by Alec-WAM** [comment]
Building the mod now. It was not liking how I was accessing the chest slot. Let me know if you find any more bugs. Thanks for the help so far!
