### ISSUE TITLE
Crystal seeds drop shards at all growth stages, not just mature

### ISSUE THREAD

**Issue by CplPibald** [Alec-WAM/CrystalMod#20]
Minecraft Version:  1.11.2
Forge Version:  2252
Mod Version:  4.7.0

Is this on a server yes/no:   n

Steps to reproduce:  
1.   Plant a crystal seed on a crystal block
2.   Break it immediately.  Get a crystal shard and a seed back.
3.   Plant seed again.  Alternate left and right click for unlimited shards

**Comment by ModCritic** [comment]
We'll get right on it.
