### ISSUE TITLE
Combining two crystal tools of the same type in a crafting table results in an item with no name or texture

### ISSUE THREAD

**Issue by CplPibald** [Alec-WAM/CrystalMod#21]
Minecraft Version: 1.11.2
Forge Version: 2252
Mod Version: 4.7.0

Steps to reproduce:  
1. Get two damaged crystal tools of the same type (but not necessarily the same color).  In my case, crystal swords from mob drops.
2. Combine them in the crafting table
3. Item that results is named "item.crystalmod.crystalsword.name" and has the magenta/black square texture.

Vanilla Minecraft adds repair recipes any tool or weapon - two damaged items of the same type becomes another item with durability equal to the sum of the two inputs.  This recipe strips all NBT data from the item (eg: it removes enchantments).   CrystalMod stores the color of the item as NBT data, so when you repair items like this you get an item with no color.

Possible solutions:
1) Override the default Minecraft recipe for two items with the same ID to preserve the color NBT
2) Use separate item IDs for each color.

**Comment by Alec-WAM** [comment]
Wow I am really impressed with your knowledge of Minecraft recipes and NBT. Ok I will look into this and try to get a fix pushed in a few days

**Comment by Alec-WAM** [comment]
Now you can repair crystal tools as long as they are the same color. It will now properly carry over the color and name too.
