### ISSUE TITLE
Can't create metal plates in survival

### ISSUE THREAD

**Issue by CplPibald** [Alec-WAM/CrystalMod#24]
Minecraft Version: 1.11.2
Forge Version: 2252
Mod Version: 4.7.0

Is this on a server: no

According to JEI:
1.   Creating metal plates requires a metal press.
2.   The recipe for a metal press requires a pipe.
3.   All of the recipes for pipes require metal plates

**Comment by ModCritic** [comment]
I knew this would happen. We'll fix it in the next update, or in the one after that because we have a lot for the coming update.
