### ISSUE TITLE
Cursed bone and cursed bonemeal have no texture

### ISSUE THREAD

**Issue by CplPibald** [Alec-WAM/CrystalMod#25]
Minecraft Version: 1.11.2
Forge Version: 2252
Mod Version: 4.7.0

Steps to reproduce:  
1.    Kill wither skeletons, get cursed bone.
2.    Turn into cursed bonemeal

**Comment by Alec-WAM** [comment]
Just fixed this in the latest release (4.8.0)

**Comment by CplPibald** [comment]
Awesome, thanks.  I'm happy to see active development here. This mod has so much potential.
