### ISSUE TITLE
Red Crystal Armor Doesn't Protect Against Fire Damage

### ISSUE THREAD

**Issue by ModCritic** [Alec-WAM/CrystalMod#30]
Minecraft Version:  1.11.2
Forge Version:  13.20.0.2228
Mod Version:  4.8.0

Is this on a server yes/no: no

Steps to reproduce:  
1.    Put On Red Crystal Armor In Survival Mode
2.   Step In Fire

**Comment by Alec-WAM** [comment]
The red crystal armor does not protect against fire. It allows you to walk across lava when you have a full suit just like blue armor and water
