### ISSUE TITLE
Dark Crystal Armor Doesn't Have Working Wither Thorns

### ISSUE THREAD

**Issue by ModCritic** [Alec-WAM/CrystalMod#32]
Minecraft Version:  1.11.2
Forge Version:  13.20.0.2228
Mod Version:  4.8.0

Is this on a server yes/no: no

Steps to reproduce:  
1.    Put On Dark Crystal Armor In Survival Mode
2.   Get Attacked

The wither thorns effect does not wither the attacker.

**Comment by Alec-WAM** [comment]
Added in 4.8.1
