### ISSUE TITLE
crash while loading a world

### ISSUE THREAD

**Issue by 0Navis0** [Alec-WAM/CrystalMod#33]
**Minecraft Version:**  1.11.2
**Forge Version:** 13.20.0.2296 
**Mod Version:** 4.8.1

**Is this on a server yes/no:**  yes

**Crash Log(s) if applicable (pastebin or git):**  https://pastebin.com/4RDzifhz

**Steps to reproduce:**  The crash happes when loading a world. Reload it doesn't change anything, the crash still happens.

**Comment by Alec-WAM** [comment]
OK I just looked at the crash and it seems that it has to do with me and how I deal with Baubles. Things should work if you start the world without Baubles installed. If that is the case I can get a fix out ASAP for that.

**Comment by Alec-WAM** [comment]
I am releasing a quick hotfix for this issue. Just update to 4.8.2
