### ISSUE TITLE
Crash after putting any item into the crystal craftingtable(s)

### ISSUE THREAD

**Issue by 0dikpah** [Alec-WAM/CrystalMod#34]
Minecraft Version:  1.11.2
Forge Version:  1.11.2-13.20.0.2296
Mod Version:  4.8.2 dev

Is this on a server yes/no:   no

[crash-2017-05-16_11.46.09-client.txt](https://github.com/Alec-WAM/CrystalMod/files/1003916/crash-2017-05-16_11.46.09-client.txt)

**Comment by Alec-WAM** [comment]
OK I just fixed the issue. It may be a little while for the fix to be released. I will have to see if I can work something out to release it.

**Comment by 0dikpah** [comment]
okay, does the mod conflict with another mod? if thats the case i can remove the mod that causing the crash..i really wanna play crystal mod!! :) one of my favorite mod so far

**Comment by Alec-WAM** [comment]
No there is no conflict. When I updated from 1.10.2 to 1.11.2 many different things changed in forge. One of those was the way that items are handled in the code. Basically it is a very simple fix but I am on vacation currently so I can't get the fixes out yet. Probably around Monday

**Comment by Alec-WAM** [comment]
OK I just added the hotfix version of 4.8.3 to the curseforge mod page. It should be available soon:tm:
