### ISSUE TITLE
Crashes When Right-Click On Furnace/Redstone/Vampiric Engine

### ISSUE THREAD

**Issue by ModCritic** [Alec-WAM/CrystalMod#35]
Minecraft Version:  1.11.2
Forge Version:  13.20.0.2228
Mod Version:  4.8.3

Is this on a server yes/no:   no

Crash Log(s) if applicable (pastebin or git):  
[https://pastebin.com/7ctWaWbi](url)

Steps to reproduce:  
1. Right-Click Any Engine

**Comment by Alec-WAM** [comment]
OK I think I just fixed this in one of the newest commits
