### ISSUE TITLE
Crash on Startup - empty string?

### ISSUE THREAD

**Issue by Mythalis** [Alec-WAM/CrystalMod#36]
Minecraft Version:  1.11.2
Forge Version:  13.20.1.2393
Mod Version:  1.11.2-4.9.0dev.jar

Is this on a server yes/no:   no

Crash Log(s) if applicable (pastebin or git):  https://pastebin.com/dEtF0sax

Steps to reproduce:  
1.    open twitch
2.   press play on the correct profile
3.  press play on minecraft launcher

**Comment by ModCritic** [comment]
I am sorry for the inconvenience, but I am now on a vacation that will take about 10 days, therefore, I will not be able to respond to any emails for that time. (This is an automatic vacation responder.)
____________________________________________________________
How To Remove Eye Bags & Lip Lines Fast (Watch)
Fit Mom Daily
http://thirdpartyoffers.juno.com/TGL3131/596b5c43e98585c4319cast01vuc

**Comment by Alec-WAM** [comment]
OK it looks like there is a problem with the CrystalMod's Liquid Ender and Thermal Expansions Liquid Ender. I will fix this in the next update to test if any other Ender Fluids are registered.

**Comment by ModCritic** [comment]
I am sorry for the inconvenience, but I am now on a vacation that will take about 10 days, therefore, I will not be able to respond to any emails for that time. (This is an automatic vacation responder.)
____________________________________________________________
Actress Maggie Q Shocks With Her Solution To Tummy Troubles
ActivatedYou
http://thirdpartyoffers.juno.com/TGL3131/59777f5f612f97f5f4245st01vuc

**Comment by Alec-WAM** [comment]
This has just finally been fixed in the newest release https://minecraft.curseforge.com/projects/crystalmod/files/2473149 (4.10) let me know if it still exists even after I tested it. Thanks for the report!
