### ISSUE TITLE
[1.11.2-4.1.0dev] Dark Iron Ingot-ception

### ISSUE THREAD

**Issue by kreezxil** [Alec-WAM/CrystalMod#4]
Liquid infuser which is required to make dark iron ingots, requires dark iron plates in its own recipe which in turn require dark iron ingots to make. This a recipe loop, or loop-ception. Therefore it is impossible to start the mod. Unless there is some undocumented way to get the dark iron ingots without the liquid infuser.

**Comment by Alec-WAM** [comment]
Dang it! OK I will re-add the nugget and iron recipe but make it more expensive to create it that way. Further encouraging the Liquid Method.
