### ISSUE TITLE
[1.11.2-4.1.0dev] dupe bug

### ISSUE THREAD

**Issue by kreezxil** [Alec-WAM/CrystalMod#5]
Since we can't make the dark iron ingot, we've been pulling things in from creative.

Discovered that the Cyrstal Fusion Pedistal will place into the world, dissappear from your hand, and continue to allow you to place it in the world.

Further you can't break, it shows that it dissappears but it doesn't reappear in your hand or hotbar, and when you try to walk through where it was you are stopped.

If you try to place another block where it was, it re-renders and shows that you didn't break it afterall.

Other players nearby can witness you doing the dupe, however they don't see you place it, until they themselves try to place a block on it or relog.

**Comment by Alec-WAM** [comment]
The dark iron ingots are craftable in the Liquid Infuser (The Machine). Does the dupe bug occur on a server? If it does could you create a single player world and try to place it in the world and see if it happens.   It sounds to me like lag.

**Comment by kreezxil** [comment]
Except you can't craft the liquid infuser, as it requires 6 dark iron plates, which are made from 6 dark iron ingots that have been made into plates.

**Comment by kreezxil** [comment]
The dupe bug occurs in smp only. :(

and I've got a small excerpt finally from a server in regards to it.

http://pastebin.com/J2B99J1E

**Comment by kreezxil** [comment]
tested in ssp and it does work properly, so it's a server issue.

**Comment by Alec-WAM** [comment]
Just updated the mod on Curse to 4.2.0. Fixing both #5 and #4. Thanks for finding the bug!

**Comment by Alec-WAM** [comment]
Also I just remembered dark iron ingots are obtained by tossing a dark shard in the crystal cauldron and dropping a iron ingot in the cauldron.
