### ISSUE TITLE
Cauldron doesn't work??

### ISSUE THREAD

**Issue by thejims** [Alec-WAM/CrystalMod#6]
Hopefully I'm just not doing it right but the Cauldron doesn't appear to do anything

Minecraft Version:  1.11.2
Forge Version:  Forge Mod Loader version 13.20.0.2226 
Mod Version:    CrystalMod-1.11.2-4.1.0dev

Is this on a server yes/no:    Both SP/MP

Crash Log(s) if applicable:  
No crash, but here are logs from running with only CrystalMod: http://pastebin.com/ntVr4FZU

Steps to reproduce:  
1.    Create Cauldron and place in world
2.   Do stuff with cauldron, right click for example should output 'Empty'?? 
3.  Nothing happens

**Comment by Alec-WAM** [comment]
First you need to toss the crystal shard of the color you want than toss the ingredient in. Right clicking should tell you how much crystal is in the cauldron.

**Comment by starky2kay13** [comment]
so yeah we try this in mp and sp and the shards and ingots just stay ontop of the cauldron

**Comment by Alec-WAM** [comment]
OK just looked at the code and it was a bug from porting to 1.11. I am building the hotfix now.

**Comment by starky2kay13** [comment]
ok thanx

**Comment by Alec-WAM** [comment]
Here is the version with the fix: https://minecraft.curseforge.com/projects/crystalmod/files/2378007

**Comment by starky2kay13** [comment]
thanx alot
